oot = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/main.go"  # явно указываем main.go
bin = "tmp/main"
full_bin = "./tmp/main"  # без лишних переменных
include_ext = ["go", "html", "tpl"]
exclude_dir = ["tmp", "vendor"]

# Включаем polling (важно для Docker!)
poll = true
poll_interval = 1000  # 1 секунда

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

# Указываем правильный порт приложения
[proxy]
enabled = false  # если не используете фронтенд-прокси